#!/usr/bin/python3
if __name__ == "__main__":
    import sys
    read_file = __import__('read_file').read_file
    find_factors = __import__('find_factors').find_factors

    num_list = read_file(sys.argv[1])
    for n in num_list:
        p = find_factors(n)
        print("{:d}={:d}*{:d}".format((p[-1] * p[0]), p[-1], p[0]))
