#!/usr/bin/python3
if __name__ == "__main__":
    import sys
    read_file = __import__('read_file').read_file
    get_prime = __import__('find_factors', 'get_prime').get_prime

    num_list = read_file(sys.argv[1])
    for n in num_list:
        f = get_prime(n)
        if len(f) == 1:
            print("{:d}={:d}*{:d}".format((f[-1] * f[0]), f[0], f[0]))
        elif len(f) == 2:
            print("{:d}={:d}*{:d}".format((f[-1] * f[0]), f[-1], f[0]))
    print()
